version: "3.3"
services:
    sqlite_db:
      image: test-db:latest
      container_name: sqlite3-db
      privileged: true
      user: "${UID}:${GID}"
      volumes: 
        - $PWD/db-docker:/db
      

  
    myAPI:
      image: rest-api:latest
      container_name: myapi-test
      privileged: true
      network_mode: host
      restart: always
      # entrypoint: "/entrypoint.sh"
      volumes: 
        - $PWD/db-docker:/home/xtract/db
     